"""

Revision ID: 6886a88de6b6
Revises: 
Create Date: 2024-10-10 00:15:07.040870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6886a88de6b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'portfolios', ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=56),
               nullable=False)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=56),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=56),
               nullable=False)
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'plan',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=56),
               nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(length=56),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=56),
               nullable=True)
    op.drop_constraint(None, 'portfolios', type_='unique')
    op.alter_column('portfolios', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('portfolios', 'type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###
